### PR TITLE
Add Seattle event

### PR DESCRIPTION
**Pull request by grant**
Planning to do a Code in the Dark in Seattle on this date.

### CODE REVIEW

**Comment by grant** [comment]
@JoelBesada @siavashg?

**Comment by JoelBesada** [comment]
Hi Grant, sorry for the late response.

We've now [added instructions to the readme](https://github.com/codeinthedark/codeinthedark.github.io#creating-the-pull-request) on how to format your pull request. Could you please follow these and update this PR?

**Comment by grant** [comment]
@JoelBesada Updated the PR according to the new format.

**Comment by JoelBesada** [comment]
Great! Could you also remove the `<p>Seattle &middot; January 2016</p>` part from the "Previous official events"? Should be good to go after that.

**Comment by grant** [comment]
Done.

**Comment by JoelBesada** [comment]
Alright! Merging this now.

**Comment by siavashg** [comment]
@grant That link seems broken or the event is closed?
Event

**Pull request merged**
