### PR TITLE
New Event

### PR DESCRIPTION
**Pull request by HiroAgustin**
Add upcoming community organized event in Montevideo.
Please feel free to delete PR #46

Thank you!

### CODE REVIEW

**Comment by ptz0n** [comment]
LGTM

**Comment by agustinkry** [comment]
Hi @siavashg,
The event is next Wednesday, would it be possible to merge the PR tomorrow?
Thank you!

**Comment by siavashg** [comment]
@HiroAgustin, @agustinkry My bad! Didn't see this until now 😢

**Comment by HiroAgustin** [comment]
That's alright, no problem 👍

**Pull request closed without merging**
